### PR TITLE
MAb feature branch updates

### PR DESCRIPTION
**Pull request by jmtaylor-fhcrc**
## Description
Two bugs were addressed here, tests were added, and updated an internal mAb variable names format was updated for consistency. The specific changes are as follows:

* An issue was discovered where queries to the server that included reserve characters for URLs in their text were not returning results properly. The root cause of that issue was found in the Rlabkey dependency, and a pull request including a fix has been made for that package, but the issue is handled here as well.

* The IC50 geometric mean for the mAb grid was not calculating properly. The calculation should return NA if all results are Inf/-Inf, and should return a value if any IC50 values are not Inf/-Inf. The calculation has been updated to reflect this requirement.

* There was a variable named `mAb_mixture` in the mAb grid. This name does not follow the casing rules of similar items, and all instances have been changed to use lower case letters.

* Tests were added and updated.

### CODE REVIEW

**Comment by juyeongkim** [comment]
## Bugs

1. Cannot create a mab object with fresh connection object.

- Repro steps:

```R
> library(DataSpaceR)
> con <- connectDS()
> mab <- con$getMab()
Error in labkey.selectRows(baseUrl = private$.config$labkeyUrlBase, folderPath = "/CAVD",  : 
  object 'mabFilters' not found
```
- Issue: There is no filter (since it's a fresh connection object), but we are trying to use `mabFilters` variable in `initialize` method in `DataSpaceMab` class.
- Solution: Add a `else` statement to assign `mabFilters` as `NULL` here
https://github.com/jmtaylor-fhcrc/DataSpaceR/blob/fb_mAb/R/DataSpaceMab.R#L33-L43


2. Warning when passing 
- Repro steps:
```R
> con$filterMabGrid(using = "hxb2_location", value = c("Env", "gp160"))
There were 19 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In get(column) == value :
  longer object length is not a multiple of shorter object length
2: In get(column) == value :
  longer object length is not a multiple of shorter object length
3: In get(column) == value :
  longer object length is not a multiple of shorter object length
4: In get(column) == value :
  longer object length is not a multiple of shorter object length
5: In get(column) == value :
  longer object length is not a multiple of shorter object length
6: In get(column) == value :
  longer object length is not a multiple of shorter object length
7: In get(column) == value :
  longer object length is not a multiple of shorter object length
8: In get(column) == value :
  longer object length is not a multiple of shorter object length
9: In get(column) == value :
  longer object length is not a multiple of shorter object length
10: In get(column) == value :
  longer object length is not a multiple of shorter object length
11: In get(column) == value :
  longer object length is not a multiple of shorter object length
12: In get(column) == value :
  longer object length is not a multiple of shorter object length
13: In get(column) == value :
  longer object length is not a multiple of shorter object length
14: In get(column) == value :
  longer object length is not a multiple of shorter object length
15: In get(column) == value :
  longer object length is not a multiple of shorter object length
16: In get(column) == value :
  longer object length is not a multiple of shorter object length
17: In get(column) == value :
  longer object length is not a multiple of shorter object length
18: In get(column) == value :
  longer object length is not a multiple of shorter object length
19: In get(column) == value :
  longer object length is not a multiple of shorter object length
```
- Solution: use `%in%` instead of `==` here
https://github.com/jmtaylor-fhcrc/DataSpaceR/blob/fb_mAb/R/DataSpaceConnection.R#L206

3.  url and user info missing in the printed summary of mab object
- Repro steps:
```R
> mab
<DataSpaceMab>
  URL:
  User:
  Summary:
    - 3 studies
    - 6 mAb mixtures
    - 7 neutralization tiers
    - 14 clades
  Filters:
    - mab_hxb2_location: Env, gp160
    - mab_donor_species: llama 
```
- Solution: change to the appropriate config variables here
https://github.com/jmtaylor-fhcrc/DataSpaceR/blob/fb_mAb/R/DataSpaceMab.R#L148-L149


## Suggestions
1. Rename `mabGridBase` field to `mabGrid`
2. Remove `retrieveMabGridValue` method (this is useless now that we can filter and retrieve via data.table syntax as you suggested in the vignette)


## Comments
Overall, good work! It's so much easier to use it now. Thanks Jason!

**Comment by juyeongkim** [comment]
## Bug

1. mismatch in `DataSpaceMab` summary and data
- Repro steps:
``` r
library(DataSpaceR)
#> By exporting data from the CAVD DataSpace, you agree to be bound by the Terms of Use available on the CAVD DataSpace sign-in page at https://dataspace.cavd.org
con <- connectDS()
con$filterMabGrid("mab_mixture", "PGT128")
mab <- con$getMab()
mab
#> <DataSpaceMab>
#>   URL: https://dataspace.cavd.org
#>   User: jkim2345@scharp.org
#>   Summary:
#>     - 2 studies
#>     - 1 mAb mixtures
#>     - 5 neutralization tiers
#>     - 14 clades
#>   Filters:
#>     - mab_mix_name_std: PGT128
mab$studies
#>    network   prot grant_pi_name investigator_name primary_poc_name
#> 1:    CAVD cvd471   Dan Barouch       Laura McCoy    Faye Stephens
#>             primary_poc_email
#> 1: fstephen@bidmc.harvard.edu
#>                                                                                                                     description
#> 1: CAVD 471 is an antibody screening study to further characterize human monoclonal antibodies from the IAVI protocol G cohort.
#>                  type            species access_level
#> 1: Antibody Screening Non-Organism Study      members
```

<sup>Created on 2019-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

- The summary shows that 2 studies are associated with this object, and the actual data shows that there are only one associated study. What's going on here?

**Comment by juyeongkim** [comment]
It looks like `retrieveMabGridValue` method is still available. My last week's suggestion was to remove `retrieveMabGridValue` method since this is useless now that we can filter and retrieve via `data.table` syntax as you suggested in the vignette.

**Comment by jmtaylor-fhcrc** [comment]
> It looks like `retrieveMabGridValue` method is still available. My last week's suggestion was to remove `retrieveMabGridValue` method since this is useless now that we can filter and retrieve via `data.table` syntax as you suggested in the vignette.

Yes, I think we should keep it for now. It might be more intuitive for some users.

**Comment by jmtaylor-fhcrc** [comment]
> ```r
> mab <- con$getMab()
> ```

This is due to a join. Write a test and fixing now.

**Review by juyeongkim — APPROVED** [review]
Looks good!

**Pull request merged**
